use std::str::FromStr;
use sha2::{Sha256, Digest as sha2_Digest};
use tss_esapi::{Context, Tcti, attributes::{ObjectAttributesBuilder, SessionAttributesBuilder}, constants::SessionType, handles::{AuthHandle, KeyHandle, ObjectHandle, SessionHandle}, interface_types::{algorithm::{HashingAlgorithm, PublicAlgorithm}, key_bits::RsaKeyBits, resource_handles::Hierarchy, session_handles::{AuthSession, PolicySession}}, structures::{Digest, HmacScheme, KeyedHashScheme, MaxBuffer, PcrSelectionListBuilder, PcrSlot, Private, Public, PublicBuilder, PublicKeyRsa, PublicKeyedHashParameters, PublicRsaParametersBuilder, RsaExponent, SensitiveData, SymmetricDefinition, SymmetricDefinitionObject}, traits::{Marshall, UnMarshall}, utils};
use zerocopy::IntoBytes;
use zeroize::Zeroizing;

const TPM_UNIQUE_KEY: &[u8] = b"pyria:tpm2:primary:v1";
pub const TPM_SALT_KEY: &[u8] = b"pyria:tpm2:salt:v1";
const PCR_SLOTS: &[PcrSlot] = &[
    PcrSlot::Slot7,   // secure boot state
    PcrSlot::Slot9,   // bootloader
    PcrSlot::Slot11,  // kernel
];

fn tpm_context() -> anyhow::Result<Context> {
    Ok(Context::new(Tcti::from_str("device:/dev/tpm0")?)?)
}

// fetch a deterministic primary key from the TPM
fn fetch_primary_key(context: &mut Context) -> anyhow::Result<KeyHandle> {

  let hash = Sha256::digest(TPM_UNIQUE_KEY);
  let mut unique = Vec::from([0u8; 256]);
  unique[..32].copy_from_slice(&hash);

  let object_attrs = ObjectAttributesBuilder::new()
    .with_fixed_tpm(true)
    .with_fixed_parent(true)
    .with_sensitive_data_origin(true)
    .with_user_with_auth(true)
    .with_decrypt(true)
    .with_sign_encrypt(false)
    .with_restricted(true)
    .build()?;

  let parent_pub = PublicBuilder::new()
    .with_public_algorithm(PublicAlgorithm::Rsa)
    .with_name_hashing_algorithm(HashingAlgorithm::Sha256)
    .with_object_attributes(object_attrs)
    .with_rsa_parameters(
      PublicRsaParametersBuilder::new_restricted_decryption_key(
        SymmetricDefinitionObject::AES_256_CFB,
        RsaKeyBits::Rsa2048,
        RsaExponent::default()
      ).build()?
    )
    .with_rsa_unique_identifier(PublicKeyRsa::try_from(unique)?)
    .build()?;

  Ok(context.create_primary(
    Hierarchy::Owner,
    parent_pub,
    None, None, None, None
  )?.key_handle)
}

// read and hash current PCR values — this is what policy_pcr expects
fn hash_current_pcrs(context: &mut Context) -> anyhow::Result<Digest> {
    let pcr_selection = PcrSelectionListBuilder::new()
        .with_selection(HashingAlgorithm::Sha256, PCR_SLOTS)
        .build()?;

    let (_, _, digests) = context.pcr_read(pcr_selection)?;

    // concatenate all PCR values then hash the result
    let concatenated = digests.value()
        .iter()
        .flat_map(|d| d.as_bytes())
        .copied()
        .collect::<Vec<u8>>();

    let (hashed, _) = context.hash(
        MaxBuffer::try_from(concatenated)?,
        HashingAlgorithm::Sha256,
        Hierarchy::Owner,
    )?;

    Ok(hashed)
}

fn make_policy_session(
    context: &mut Context,
    session_type: SessionType,
) -> anyhow::Result<PolicySession> {
    let session = context.start_auth_session(
        None, None, None,
        session_type,
        SymmetricDefinition::AES_256_CFB,
        HashingAlgorithm::Sha256,
    )?.ok_or_else(|| anyhow::anyhow!("no session returned"))?;

    // enable encrypt+decrypt on session
    let (attrs, mask) = SessionAttributesBuilder::new()
        .with_decrypt(true)
        .with_encrypt(true)
        .build();
    context.tr_sess_set_attributes(session, attrs, mask)?;

    Ok(PolicySession::try_from(session)?)
}

pub struct TpmHmacKey {
    pub private: Vec<u8>,
    pub public:  Vec<u8>,
}

// at enrollment: create a PCR-bound HMAC key inside the TPM
// the key material is generated by the TPM and never leaves it
pub fn create_hmac_key() -> anyhow::Result<TpmHmacKey> {
    let mut ctx = tpm_context()?;
    let parent = fetch_primary_key(&mut ctx)?;

    let pcr_hash = hash_current_pcrs(&mut ctx)?;
    let pcr_selection = PcrSelectionListBuilder::new()
        .with_selection(HashingAlgorithm::Sha256, PCR_SLOTS)
        .build()?;

    ctx.clear_sessions();
    let trial_session = make_policy_session(&mut ctx, SessionType::Trial)?;
    ctx.policy_pcr(trial_session, pcr_hash, pcr_selection)?;
    let policy_digest = ctx.policy_get_digest(trial_session)?;
    ctx.flush_context(SessionHandle::from(trial_session).into())?;

    let obj_attrs = ObjectAttributesBuilder::new()
        .with_fixed_tpm(true)
        .with_fixed_parent(true)
        .with_sensitive_data_origin(true)
        .with_user_with_auth(true)
        .with_no_da(true)
        .with_admin_with_policy(true)
        .with_sign_encrypt(true)
        .build()?;

    let hmac_key_pub = PublicBuilder::new()
        .with_public_algorithm(PublicAlgorithm::KeyedHash)
        .with_name_hashing_algorithm(HashingAlgorithm::Sha256)
        .with_object_attributes(obj_attrs)
        .with_auth_policy(policy_digest)
        .with_keyed_hash_parameters(PublicKeyedHashParameters::new(
            KeyedHashScheme::Hmac {
                hmac_scheme: HmacScheme::new(HashingAlgorithm::Sha256)
            }
        ))
        .with_keyed_hash_unique_identifier(Default::default())
        .build()?;

    let hmac_session = ctx.start_auth_session(
        None, None, None,
        SessionType::Hmac,
        SymmetricDefinition::AES_256_CFB,
        HashingAlgorithm::Sha256,
    )?.ok_or_else(|| anyhow::anyhow!("no hmac session"))?;
    ctx.set_sessions((Some(hmac_session), None, None));

    let result = ctx.create(
        parent,
        hmac_key_pub,
        None,
        None,
        None,
        None,
    )?;

    ctx.flush_context(SessionHandle::from(hmac_session).into())?;
    ctx.flush_context(parent.into())?;

    Ok(TpmHmacKey {
        private: result.out_private.to_vec(),
        public:  result.out_public.marshall()?,
    })
}

// at unlock: equivalent to the FIDO2 hmac() function
// input is the argon2id output, output is 32 bytes of TPM-internal HMAC
pub fn hmac(key: &TpmHmacKey, input: &[u8]) -> anyhow::Result<Zeroizing<[u8; 32]>> {
    let mut ctx = tpm_context()?;
    let parent = fetch_primary_key(&mut ctx)?;

    // load the HMAC key
    let private = Private::try_from(key.private.clone())?;
    let public  = Public::unmarshall(key.public.as_slice())?;
    let key_handle = ctx.load(parent, private, public)?;

    // policy session — verifies current PCRs match enrollment state
    let pcr_hash = hash_current_pcrs(&mut ctx)?;
    let pcr_selection = PcrSelectionListBuilder::new()
        .with_selection(HashingAlgorithm::Sha256, PCR_SLOTS)
        .build()?;

    ctx.clear_sessions();
    let policy_session = make_policy_session(&mut ctx, SessionType::Policy)?;
    ctx.policy_pcr(policy_session, pcr_hash, pcr_selection)?;

    ctx.set_sessions((
        Some(AuthSession::PolicySession(policy_session)),
        None,
        None,
    ));

    let key_handle = ObjectHandle::from(key_handle);

    // ask the TPM to HMAC our input — key never leaves the chip
    let result = ctx.hmac(
        key_handle,
        MaxBuffer::try_from(input.to_vec())?,
        HashingAlgorithm::Sha256,
    )?;

    ctx.flush_context(SessionHandle::from(policy_session).into())?;
    ctx.flush_context(key_handle)?;
    ctx.flush_context(parent.into())?;

    let bytes = result.as_bytes();
    anyhow::ensure!(bytes.len() == 32, "unexpected hmac length from TPM");
    let mut out = Zeroizing::new([0u8; 32]);
    out.copy_from_slice(bytes);
    Ok(out)
}